use_frameworks!

def common_pods
  pod 'DataManager', :path => '../'
end

target 'DataManager_Example', :exclusive => true do
  common_pods
end

target 'DataManager_Tests', :exclusive => true do
  common_pods

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
end
