use_frameworks!

def common_pods
  pod 'DataManager', :path => '../'
end

target 'DataManager_Example' do
  platform :ios, '8.0'
  common_pods
end

target 'Data_Populator' do
  platform :osx, '10.10'
  common_pods
end

target 'DataManager_Tests' do
  platform :ios, '8.0'
  common_pods

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
end
